### ISSUE TITLE
About fonts in the poster 

### ISSUE THREAD

**Issue by jiaweihe1996** [hiyouga/AMP-Poster-Slides-LaTeX#1]
HI!
In the poster requirements on the Harvester website, the fonts in the poster should be sans-serif. However, the default font in the LaTeX template is TimesNewRoman, a kind of Serif font. Is there any idea to deal with it?
Thank you very much.

**Comment by hiyouga** [comment]
Please comment the two lines in L36-37 and add this line to L38, then you can switch to using sans-serif for everything except mathematics. The default sans-serif font would be Computer Modern, you can also put `\usepackage{helvet}` for switching to Helvetica or `\usepackage{avant}` for Avant-Garde[1].
```latex
% \renewcommand{\rmdefault}{ptm} % Arial
% \renewcommand{\sfdefault}{ptm} % Arial
\renewcommand{\familydefault}{\sfdefault}
```
[1] https://tex.stackexchange.com/questions/2095/what-is-the-simplest-way-to-typeset-an-entire-document-in-sans-serif

**Comment by jiaweihe1996** [comment]
I got it. Thx.
